version: "3"

services:
  node:
    image: node:16
    container_name: escribo_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    user: node:node
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3005:3005
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secretJWT
      API_HOST: 'node'
      API_PORT: 3001
      NODE_ENV: 'development'
    networks:
      - escribo_api_net

  db:
    container_name: escribo_db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - escribo_api_net

networks:
  escribo_api_net:
    driver: bridge